### ISSUE TITLE
Unable to configure  TXT records that are longer than 255

### ISSUE THREAD

**Issue by Limorerez** [gardener/dnslb-controller-manager#7]
**What would you like to be added**:
We currently having issues with creating TXT record with over 255 characters in Route53.
We would appreciate it if you could follow AWS guidelines for management of TXT records that are longer than 255 chars( i.e. "splitting the string into multiple 255-char strings, a TXT value of up to 4000 chars is supported. ") 
Guidelines: https://aws.amazon.com/premiumsupport/knowledge-center/route-53-configure-long-spf-txt-records/#:~:text=A%20TXT%20record%20contains%20one,TXT%20record%20is%204%2C000%20characters.”  

**Why is this needed**:
The way we generate these records it sometimes exceeds 255 chars 

Best regards,
Limor

**Comment by MartinWeindel** [comment]
Wrong project.
You probably meant https://github.com/gardener/external-dns-management
